"""add user_id to contacts and per-user email uniqueness

Revision ID: a4e0175af643
Revises: 2c2664b73a1a
Create Date: 2026-06-04 09:57:31.682675

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4e0175af643"
down_revision: Union[str, Sequence[str], None] = "2c2664b73a1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=False)
    op.create_index(op.f("ix_contacts_user_id"), "contacts", ["user_id"], unique=False)
    op.create_unique_constraint("uq_contacts_user_email", "contacts", ["user_id", "email"])
    op.create_foreign_key(
        "fk_contacts_user_id_users", "contacts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_contacts_user_id_users", "contacts", type_="foreignkey")
    op.drop_constraint("uq_contacts_user_email", "contacts", type_="unique")
    op.drop_index(op.f("ix_contacts_user_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=True)
    op.drop_column("contacts", "user_id")
    # ### end Alembic commands ###
